require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - public/**/*
    - tmp/**/*
    - log/**/*

Rails:
  Enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# ファイルの先頭にコメントが必要
Style/FrozenStringLiteralComment:
  Enabled: false

# 英語でコメントが記載されているかどうかをチェック
Style/AsciiComments:
  Enabled: false

# メソッドの行数チェック
Metrics/MethodLength:
  Max: 11

# ブロックの長さをチェック
Metrics/BlockLength:
  Exclude:
    - spec/**/*

# ネストされたグループをチェック
RSpec/NestedGroups:
  Max: 4

# 日本語だと「〜の場合」になるので suffix でないと対応できない
RSpec/ContextWording:
  Enabled: false

# spec内のファイルパスが一致しているかチェック
RSpec/FilePath:
  Enabled: false
