require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - public/**/*
    - tmp/**/*
    - log/**/*
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  # RunRailsCops: true
Rails:
  Enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
